// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYc3vXdY53DxsIqnMIN8MvlYHmAS82tE',
    appId: '1:513271994370:web:d6e610b87f3d56d8ae2f1b',
    messagingSenderId: '513271994370',
    projectId: 'chat-app-f655c',
    authDomain: 'chat-app-f655c.firebaseapp.com',
    storageBucket: 'chat-app-f655c.appspot.com',
    measurementId: 'G-TFGHZBKMW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3D1T_03dNUs_hKSexcFkmZnWYQP3NhuY',
    appId: '1:513271994370:android:1fdc5751940c9fb0ae2f1b',
    messagingSenderId: '513271994370',
    projectId: 'chat-app-f655c',
    storageBucket: 'chat-app-f655c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6QJVN8ykENfnj_B-iiIfyDCDQalz29gI',
    appId: '1:513271994370:ios:e98282869ac381b4ae2f1b',
    messagingSenderId: '513271994370',
    projectId: 'chat-app-f655c',
    storageBucket: 'chat-app-f655c.appspot.com',
    iosClientId: '513271994370-u4t77hd0kik95ca0pd702isjpe5qlcdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6QJVN8ykENfnj_B-iiIfyDCDQalz29gI',
    appId: '1:513271994370:ios:f5f2b61576d8ef10ae2f1b',
    messagingSenderId: '513271994370',
    projectId: 'chat-app-f655c',
    storageBucket: 'chat-app-f655c.appspot.com',
    iosClientId: '513271994370-do1ecuiv8uioq3p451j6ok3knocompas.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
